# Generated by Django 4.2.4 on 2024-02-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Roll', models.IntegerField()),
                ('City', models.CharField(max_length=15)),
            ],
        ),
    ]
